### ISSUE TITLE
下载的时候能否判断已经有的歌词直接跳过？没必要重复下载。

### ISSUE THREAD

**Issue by liuzhaoyzz** [chenmozhijin/LDDC#22]
下载的时候能否判断已经有的歌词直接跳过？没必要重复下载。

**Comment by chenmozhijin** [comment]
已在[v0.9.0](https://github.com/chenmozhijin/LDDC/releases/tag/v0.9.0)版本中实现

**Comment by liuzhaoyzz** [comment]
感谢更新！

**Comment by liuzhaoyzz** [comment]
LDDC-0.9.0-windows-amd64，在win10x64下面，LDDC.exe打不开啊，双击之后，没有任何反应，是咋回事？运行库我之前都安装过了的。

**Comment by chenmozhijin** [comment]
看一下有没有日志C:\Users\{你的用户名}\AppData\Local\LDDC\Logs

**Comment by liuzhaoyzz** [comment]
C:\Users\Administrator\AppData\Local\LDDC\Logs
只有前一个版本的log，最新版本的没有log文件。

**Comment by liuzhaoyzz** [comment]
C：\Users\Administrator\AppData\Local\LDDC\Logs，这个目录我删除之后，0.9版本运行之后，没有产生这个目录了，也没有log。

**Comment by chenmozhijin** [comment]
0.9.0版本一次都没有打开过吗？检查一下任务管理器，有没有正在运行的LDDC

删除这两个文件夹看看(会删除**所有**LDDC的配置、数据，包括所有歌词关联与桌面歌词自动保存的歌词)
C:\Users\Administrator\AppData\Local\LDDC
C:\Users\Administrator\AppData\Roaming\LDDC

我试了一下微步在线云沙箱的Win10(1903 64bit)是打得开的
https://s.threatbook.com/report/file/c77c6346f7a3224ab2407a60516587b71543958c4bc86ec32aa89ae04dd82d71
![Image](https://github.com/user-attachments/assets/ddd928e8-cd73-4db0-b94f-66271845e153)

**Comment by liuzhaoyzz** [comment]
你说的这两个目录我都删除了，还是无法打开。也没有再次创建log文件。
进程中没有LDDC.exe的进程，电脑都重启了，也不行。

**Comment by chenmozhijin** [comment]
尝试用命令行运行`.\LDDC.exe --get-service-port`试试，看看能不能输出错误或者端口号

**Comment by liuzhaoyzz** [comment]
G:\LDDC-0.9.0-windows-amd64\LDDC>.\LDDC.exe --get-service-port

G:\LDDC-0.9.0-windows-amd64\LDDC>Exception ignored in: 'PySide6-postLoad'
Traceback (most recent call last):
  File "G:\LDDC-0~1.0-W\LDDC\PySide6-postLoad.py", line 26, in <module PySide6-postLoad>
ImportError:
Traceback (most recent call last):
  File "G:\LDDC-0~1.0-W\LDDC\__main__.py", line 7, in <module>
ImportError

G:\LDDC-0.9.0-windows-amd64\LDDC>

**Comment by liuzhaoyzz** [comment]
为啥会有删除线，回帖

**Comment by chenmozhijin** [comment]
这实在是我没有见过的错误，看着是[Nuitka](https://github.com/Nuitka/Nuitka)或PySide6的问题，这是单文件版吗，如果是的话试试独立版，看错误输出是不是一模一样

这是一个最新的打包的独立版(里面的LDDC-0.9.0-windows-amd64.zip)https://github.com/chenmozhijin/LDDC/actions/runs/14951862693/artifacts/3100480261  
如果还不行只能试试[用python运行](https://github.com/chenmozhijin/LDDC/wiki/%E4%B8%8B%E8%BD%BD%E4%B8%8E%E8%BF%90%E8%A1%8C#4%E4%BD%BF%E7%94%A8python%E8%BF%90%E8%A1%8C)了

**Comment by liuzhaoyzz** [comment]
我用的是独立版，上面有截图啊，不是onefile。
下载了你楼上的版本，运行后也是一样的结果。打不开

G:\Windows - x64 artifacts\LDDC-0.9.0-windows-amd64\LDDC>.\LDDC.exe --get-service-port

G:\Windows - x64 artifacts\LDDC-0.9.0-windows-amd64\LDDC>Exception ignored in: 'PySide6-postLoad'
Traceback (most recent call last):
  File "G:\WINDOW~1\LDDC-0~1.0-W\LDDC\PySide6-postLoad.py", line 26, in <module PySide6-postLoad>
ImportError:
Traceback (most recent call last):
  File "G:\WINDOW~1\LDDC-0~1.0-W\LDDC\__main__.py", line 7, in <module>
ImportError

G:\Windows - x64 artifacts\LDDC-0.9.0-windows-amd64\LDDC>

**Comment by liuzhaoyzz** [comment]
我安装python之后，为啥找不到python.exe，要怎么加到环境变量中？我看了下是安装到了C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe。

python -m LDDC

G:\Windows - x64 artifacts\LDDC-0.9.0-windows-amd64\LDDC>python
'python' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

G:\Windows - x64 artifacts\LDDC-0.9.0-windows-amd64\LDDC>C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe -m LDDC
C:\Users\Administrator\AppData\Local\Programs\Python\Python313\python.exe: No module named LDDC

**Comment by liuzhaoyzz** [comment]
带上python长路径运行LDDC，也不行啊，提示 No module named LDDC，LDDC.exe所在的文件夹，我已经切换过去了。

能否看下倒底是什么原因？安装python，用python运行太麻烦了。

**Comment by liuzhaoyzz** [comment]
哦，细看了下还要下载源码，安装依赖啊，有点麻烦，github下载速度太慢了。
